# Generated by Django 5.0.6 on 2024-06-22 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeberries',
            name='cashier',
        ),
        migrations.AddField(
            model_name='coffeeberries',
            name='date_collected',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
