# Generated by Django 3.2.12 on 2024-05-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_address_farmer_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='berry_weight',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeBerries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.field')),
            ],
        ),
    ]
