# Generated by Django 5.0.6 on 2024-07-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_coffeeberries_cashier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeberries',
            name='coffe_type',
            field=models.CharField(choices=[('cherry', 'Cherry'), ('mbuni', 'Mbuni')], max_length=100, null=True),
        ),
    ]
