# Generated by Django 5.0.6 on 2024-07-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_coffeeberries_coffe_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeberries',
            name='coffe_type',
        ),
        migrations.RemoveField(
            model_name='coffeeberries',
            name='date_collected',
        ),
        migrations.AddField(
            model_name='coffeeberries',
            name='berry_type',
            field=models.CharField(choices=[('cherry', 'Cherry'), ('mbuni', 'Mbuni')], default=True, max_length=10),
        ),
    ]
