# Generated by Django 3.2.12 on 2024-05-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20240521_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='coffe_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffeeberries',
            name='weight',
            field=models.FloatField(),
        ),
    ]
