# Generated by Django 5.0.6 on 2024-07-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_coffeeberries_coffe_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CherryWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.field')),
            ],
        ),
        migrations.CreateModel(
            name='MbuniWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.field')),
            ],
        ),
        migrations.DeleteModel(
            name='CoffeeBerries',
        ),
    ]
