# Generated by Django 5.0.6 on 2024-08-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_harvest_season_farmer_agreement_field_harvest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(default='Unamed Payment', max_length=200),
        ),
    ]
