# Generated by Django 5.0.6 on 2024-08-14 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_payment_payment_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.CharField(max_length=1, null=True)),
                ('berry_type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kilo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_number', models.CharField(max_length=200, unique=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.farmer')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.harvest')),
            ],
        ),
    ]
