# Generated by Django 5.0.6 on 2024-08-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_newpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpayment',
            name='payment_number',
            field=models.CharField(max_length=200),
        ),
    ]
