# Generated by Django 3.2.12 on 2024-07-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_farmer_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoffeeBerries',
            new_name='CherryWeight',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='MbuniWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.field')),
            ],
        ),
    ]
