# Generated by Django 3.2.12 on 2024-10-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_newpayment_payment_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
