# Generated by Django 3.2.12 on 2024-07-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_harvest_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='name',
            field=models.CharField(default='Harvest', max_length=100),
        ),
    ]
