# Generated by Django 3.2.12 on 2024-07-24 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_harvest_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectedHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.harvest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
