# Generated by Django 3.2.12 on 2024-07-24 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_userselectedharvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='harvest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.harvest'),
        ),
    ]
